#!/bin/sh -f

## a script to run OLMT (https://github.com/dmricciuto/OLMT.git, branch 'Arctic-userpft'), for simulation using GSWP3_daymet driving forcing and 
## specific domain/surface dataset (generated by 'makepointdata.py'). 

# 1) E3SM input data root directory

E3SM_INPUT=/Users/f9y/clm4_5_inputdata

# 2) E3SM model directory. Please clone/checkout E3SM branch: 
## https://github.com/E3SM-Project/E3SM.git, branch 'fmyuan/lnd/elm-dgx'
E3SM_ROOT=/Users/f9y/mygithub/E3SM

# 3) GSWP3-daymet datasets
## copy GSWP3-daymet forcing - 'cpl_bypass_full/', and, relevant files - 'domain.nc', 'surfdata.nc', and 'surfdata.pftdyn.nc'.
USER_METDIR=/Users/f9y/clm4_5_inputdata/atm/datm7/GSWP3_daymet/TILE13868

DAYMETTILE=TILE13868

# 4) (optional) case root and run root directories
CASE_ROOT=/Users/f9y/project_acme/cases
RUN_ROOT=/Users/f9y/project_acme/scratch

# 5) run the following from OLMT directory. NOTE: modify '--machine xxx', '--compiler xxx', '--mpilib xxx', and '--np xx', as what machine and environmental settings for E3SM. ' --no_submit' implies cases will not submit for running, so it's optional. 

python ./global_fullrun.py \
 --caseidprefix ELM-${DAYMETTILE} \
 --nyears_ad_spinup 200 --nyears_final_spinup 600 --tstep 1 \
 --machine mymac --compiler gnu --mpilib mpich \
 --cpl_bypass --spinup_vars \
 --gswp3 --daymet4 \
 --model_root ${E3SM_ROOT} \
 --caseroot ${CASE_ROOT} \
 --nopointdata \
 --metdir ${USER_METDIR}/cpl_bypass_full \
 --domainfile ${USER_METDIR}/domain.nc \
 --surffile ${USER_METDIR}/surfdata.nc \
 --landusefile ${USER_METDIR}/surfdata.pftdyn.nc \
 --np 1 \
 --ccsm_input ${E3SM_INPUT} \
 --runroot ${RUN_ROOT} \
 --no_submit

