#!/bin/sh -f

#source ~/.bashrc

## a script to run OLMT (https://github.com/dmricciuto/OLMT.git, branch 'Arctic-userpft'), 
## for simulation using CPL_BYPASS Daymet-ERA5 or GSWP3-daymet driving forcing and 
## specific domain/surface dataset (generated by 'makepointdata.py'). 

# 1) E3SM input data root directory on cades-baseline

E3SM_INPUTDATA=/gpfs/wolf2/cades/cli185/world-shared/e3sm/inputdata

# 2) E3SM model directory. Please clone/checkout E3SM folked and its branch for NGEE-Arctic project: 
## https://github.com/ORNLngee/E3SM_ORNL_IM, branch 'ngee-arctic-IM-merged'
E3SM_ROOT=/Users/f9y/mygithub/E3SM_REPOS/E3SM_ORNL_IM

# 3) ONE of following offline ELM forcing data sets

# 3a) half-degree GSWP3 v2

if [ $1 == 1 ]; then

	CASEID=TFSmeq2_GSWP3
	USER_METDIR=${E3SM_INPUTDATA}/atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v2.c180716_NGEE-Grid/atm_forcing.datm7.GSWP3.0.5d.v2.c180716_ngee-TFS-Grid/cpl_bypass_full
	USER_domain=${USER_LNDDIR}/domain.lnd.r05_RRSwISC6to18E3r5.240328_meq2.nc
	USER_surfdata=${USER_LNDDIR}/surfdata_0.5x0.5_simyr1850_c240308_TOP_meq2.nc
	NYRS_TRANS=165
	NP=2
	NPP=2
	MET_TYPES='--cpl_bypass --gswp3 '

elif [ $1 == 2 ]; then
# OR, 1km2 GSWP3-daymet datasets
	CASEID=TFSmeq2_GSWP3daymet
	USER_METDIR=${E3SM_INPUTDATA}/atm/datm7/GSWP3_daymet_ngee4/cpl_bypass_ngee-TFSmeq2
	USER_LNDDIR=${E3SM_INPUTDATA}/atm/datm7/GSWP3_daymet_ngee4/cpl_bypass_ngee-TFSmeq2
	USER_domain=${USER_LNDDIR}/domain.lnd.pan-arctic_CAVM.1km.1d.c241018_TFSmeq2.nc
	USER_surfdata=${USER_LNDDIR}/surfdata_pan-arctic_CAVM.1km.1d_simyr1850_c240308_TOP_TFSmeq2_newfrac.nc
	NYRS_TRANS=165
	NP=4
	PPN=4
	MET_TYPES="--cpl_bypass --gswp3 --daymet4"

elif [ $1 == 3 ]; then
# OR, 1km2 ERA5-dayment datasets
	CASEID=TFSmeq2_ERA5daymet
	USER_METDIR=${E3SM_INPUTDATA}/atm/datm7/Daymet_ERA5_ngee4/cpl_bypass_ngee-TFSmeq2
	USER_LNDDIR=${E3SM_INPUTDATA}/atm/datm7/Daymet_ERA5_ngee4/cpl_bypass_ngee-TFSmeq2
	USER_domain=${USER_LNDDIR}/domain.lnd.pan-arctic_CAVM.1km.1d.c241018_TFSmeq2.nc
	USER_surfdata=${USER_LNDDIR}/surfdata_pan-arctic_CAVM.1km.1d_simyr1850_c240308_TOP_TFSmeq2_newfrac.nc
	NYRS_TRANS=174
	NP=4
	PPN=4
	MET_TYPES="--cpl_bypass --era5 --daymet4"

else
   echo "ERROR: require 1, 2, or 3 as an input"
   echo ''
   exit 2

fi;

# 4) (optional) case root and run root directories
CASE_ROOT=/gpfs/wolf2/cades/cli185/proj-shared/${USER}/project-e3sm/cases
RUN_ROOT=/gpfs/wolf2/cades/cli185/scratch/${USER}

# 5) run the following from OLMT directory. NOTE: modify '--machine xxx', '--compiler xxx', '--mpilib xxx', and '--np xx', as what machine and environmental settings for E3SM. ' --no_submit' implies cases will not submit for running, so it's optional. 

python ./site_fullrun.py \
 --site AK-TFSG --sitegroup NGEEArctic \
 --caseidprefix ELMngee4_${CASEID} \
 --nyears_ad_spinup 200 --nyears_final_spinup 600 --nyears_transient ${NYRS_TRANS} --tstep 1 \
 --machine cades-baseline --compiler gnu --mpilib openmpi-amanzitpls \
 --walltime 12 \
 ${MET_TYPES} \
 --spinup_vars \
 --model_root ${E3SM_ROOT} \
 --caseroot ${CASE_ROOT} \
 --nopointdata \
 --nopftdyn \
 --metdir ${USER_METDIR} \
 --domainfile ${USER_domain} \
 --surffile ${USER_surfdata} \
 --nopftdyn \
 --np ${NP} --ppn ${PPN} \
 --ccsm_input ${E3SM_INPUTDATA} \
 --runroot ${RUN_ROOT}

